# 1. Usar el host IPv4 del Pooler en lugar de la conexión directa
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?user=postgres.wzbqhmdfumxqxbksggoa&password=f5qbN6kAGcwoC4F0

spring.jpa.hibernate.ddl-auto=update

# 4. Driver y Dialecto explícitos para evitar errores de arranque
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect