# Configuración de Base de Datos H2 en Memoria
spring.datasource.url=jdbc:h2:mem:pesodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola web de H2 (opcional, para ver las tablas desde el navegador)
spring.h2.console.enabled=true